name: Provence
favicon: null
layout_spectrum: 0.99784
typography_spectrum: 0.80303
title: La Petite Provence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030300'
    - '#ffbe00'
    - '#9e3700'
    - '#af9c88'
    - '#ffcdff'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
