name: La Petite Provence
favicon: null
layout_spectrum: 0.24936
typography_spectrum: 0.06836
title: La Petite Provence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#88a0d3'
    - '#b6cceb'
    - '#657aa2'
    - '#526587'
    - '#425471'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
